# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: zzzzzz123
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: message-board-test
service: serverless-http-api

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-2 
  environment: #use environment variable for future extend
    USER_REG_TOPIC: user-registration-topic
    USERS_TABLE: Users
    AWS_ACCOUNT_ID: ${aws:accountId}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sns:Publish
      Resource:
        - arn:aws:sns:${aws:region}:${aws:accountId}:${self:provider.environment.USER_REG_TOPIC}



resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: USERS_TABLE
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH

functions:
  registerUser:
    handler: src/registerUser.handler
    events:
      - httpApi:
          method: POST
          path: /register
  handleUserRegistration:
    handler: src/handleUserRegistration.handler
    events: 
      - sns: USER_REG_TOPIC
  getUserByEmail:
    handler: src/getUserByEmail.handler
    events:
      - httpApi:
          method: GET
          path: /user/{email}
