# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: zzzzzz123
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: message-board-test
service: serverless-http-api

provider:
  name: aws
  runtime: nodejs20.x

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
