# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: zzzzzz123
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: message-board-test
service: serverless-http-api

provider:
  name: aws
  runtime: nodejs20.x
  environment: #use environment variable for future extend
    USER_REG_TOPIC: ${self.service}-user-registration-topic

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get

functions:
  registerUser:
    handler: src/registerUser.handler
    events:
      - httpApi: 'POST /register'
  
  handleUserRegistration:
    handler: src/handleUserRegistration.handler
    events: 
      -sns: ${self:provider.environment.USER_REG_TOPIC}

  getUserByEmail:
    handler: src/getUserByEmail.handler
    events:
      - httpApi: 'GET user/{email}'

